{% set name = "streamlit-faker" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bff0f053aa514a99313a3699746183b41111891c82d6e9b41b1c69a7d719bf2f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<36]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=61.0
  run:
    - python
    - streamlit
    - streamlit-extras
    - faker
    - matplotlib-base

test:
  imports:
    - streamlit_faker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/arnaudmiribel/streamlit-faker
  dev_url: https://github.com/arnaudmiribel/streamlit-faker
  doc_url: https://github.com/arnaudmiribel/streamlit-faker/blob/main/README.md
  summary: streamlit-faker is a library to very easily fake Streamlit commands
  description: |
    This repository introduces streamlit-faker, a library to very easily fake Streamlit 
    commands. You can use it to quickly draft a user interface or as a QA tool... or maybe 
    something more (let us know!). It is built upon the great joke2k/faker project!
  license: Apache-2.0
  # TODO license file was ommitted from v0.0.2
  # license_file: LICENSE.md
  license_url: https://github.com/arnaudmiribel/streamlit-faker/blob/main/LICENSE.md
  license_family: Apache

extra:
  recipe-maintainers:
    - ELundby45
